function(AZ3D_DATA_COPY target OUTPUT_DIR)
	file(GLOB_RECURSE AZ3D_DATA_FILES
		RELATIVE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/data"
		CONFIGURE_DEPENDS
		"${CMAKE_CURRENT_FUNCTION_LIST_DIR}/data/*"
	)
	foreach(AZ3D_DATA_FILE ${AZ3D_DATA_FILES})
		add_custom_command(OUTPUT "${OUTPUT_DIR}/data/Az3D/${AZ3D_DATA_FILE}"
			COMMAND echo "Copying Az3D data/${AZ3D_DATA_FILE} to ${target}"
			COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/data/${AZ3D_DATA_FILE}" "${OUTPUT_DIR}/data/Az3D/${AZ3D_DATA_FILE}"
			DEPENDS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/data/${AZ3D_DATA_FILE}"
		)
		target_sources(${target} PRIVATE "${OUTPUT_DIR}/data/Az3D/${AZ3D_DATA_FILE}")
	endforeach(AZ3D_DATA_FILE)
endfunction()